sut:
  container_name: statping_sut
  build: .
  dockerfile: Dockerfile.test
  links:
    - statping
statping:
  build: .
  dockerfile: Dockerfile
  environment:
    DB_CONN: sqlite
    NAME: Docker Tester
